export const CHAT_INITIAL_PEER_SESSION_KEY = 'pubky2pubky-chat:initial-peer';

export const CHAT_SEARCH_RESULT_LIMIT = 8;
export const CHAT_SEARCH_DEBOUNCE_MS = 300;
export const CHAT_SEARCH_QUERY_MAX_LENGTH = 128;

export const CHAT_MESSAGE_MAX_BYTES = 4096;
export const CHAT_MESSAGE_ID_MAX_LENGTH = 128;
export const CHAT_TRANSPORT_EPOCH_MAX_LENGTH = 64;
export const CHAT_TRANSPORT_MAX_FUTURE_SKEW_MS = 5 * 60 * 1000;
export const CHAT_AUTHORIZATION_URL_MAX_LENGTH = 2048;
export const CHAT_MAX_MESSAGES_PER_CONVERSATION = 500;
export const CHAT_MAX_CONVERSATIONS = 100;
